---
# Combined NodePort Service for direct mobile testing
# Use this instead of Ingress if ingress-nginx is not available
apiVersion: v1
kind: Service
metadata:
  name: pre-shift-check-nodeport
  namespace: pre-shift-check
  labels:
    app: pre-shift-check
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: client
  selector:
    app: pre-shift-check
    component: client

